### ISSUE TITLE
support remotebase

### ISSUE THREAD

**Issue by fishbar** [node-cube/cube#26]
## 服务端变更

* 更改build的wraper: `Cube(moduleName, [require], callback, namespace)`， 只影响到build环节
* `process_js` 解析require中的路径 `require("remote:/asdfad")`
* 引用远端脚本的文件，编译之后`Cube(moduleName, [['remote', path]], callback, namespace)`

### wraper函数更新，支持namespace参数，但保持和requireJS的风格兼容
```
Cube(moduleName, [a, b, c], callback, namespace);
```

### 初始化增加 `remoteBase` 选项，该选项为Object，支持多源

```
Cube.init({
   ....
   remoteBase: {
     'remoteAlias': 'http://remote_real_path'
   }
   ....
});
```

**Comment by cwtuan** [comment]
Cube('a.js', [['remote', '/com/test.js'], '/com/b.js'], callback, namespace);

**Comment by cwtuan** [comment]
require('remote:/com/xxx.js');
async('remote:/com/xxx.css');

**Comment by cwtuan** [comment]
Cube.init({
   remoteBase: {
     'remoteA': 'http://remote_real_pathA',
     'remoteB': 'http://remote_real_pathB',
   }
});
require('remoteA:/com/xxx.js');
async('remoteB:/com/xxx.css');
编译时解析成：
Cube('a.js', [['remoteA', '/com/xxx.js'], '/com/b.js'], callback, namespace);
namespace是什么？

**Comment by fishbar** [comment]
done
