### ISSUE TITLE
前端打包压缩

### ISSUE THREAD

**Issue by zhouningyi** [node-cube/cube#32]
希望增加前端js打包合并压缩的功能 并可以有是否uglify、css的压缩策略等压缩选项。

**Comment by zhouningyi** [comment]
gulp和grunt 都有个xxxfile的文件，指导怎么进行打包 感觉挺好..

**Comment by rockdai** [comment]
这事儿不应该由cube来做吧

**Comment by zhouningyi** [comment]
cube现在是带有这些类似的功能的

**Comment by rockdai** [comment]
我是说定义xxx file这种事。。
