### ISSUE TITLE
Cube Error: Cannot find module './debug'

### ISSUE THREAD

**Issue by HQidea** [node-cube/cube#55]
debug 模块browser.js line8: `require('./debug')`没有提取到依赖列表

debug v2.2.0

**Comment by fishbar** [comment]
### 问题排查情况：

实际反应的bug是：
* 当映射了modulemap之后， 需要将模块名替换成映射的文件名，以保证其相对依赖模块的路劲正确

另外发现的一个问题：
* 当模块重新定义了load方法，会导致require方法的依赖文件无法解析。识别redefined的时候逻辑有缺陷
